#!/bin/bash

cp ~/.config/compton.conf ~/Dropbox/dotfiles/compton.conf && echo "updated comton.conf"
cp ~/.config/picom.conf ~/Dropbox/dotfiles/picom.conf && echo "updated comton.conf"
cp ~/.config/i3/config ~/Dropbox/dotfiles/i3/config && echo "updated i3/config"
cp ~/.Xresources ~/Dropbox/dotfiles/.Xresources && echo "updated .Xresources"
cp ~/.bashrc ~/Dropbox/dotfiles/.bashrc && echo "updated .bashrc"
cp -rfa ~/Scripts ~/Dropbox/dotfiles/ && echo "updated Scripts/"
cp ~/.vimrc ~/Dropbox/dotfiles/.vimrc && echo "updated .vimrc"

cd ~/Scripts/
if [[ $(git status --porcelain) ]]
then
    notify-send -t 0 -u critical "Files in ~/Scripts/ have been changed. Please push changes to github."
fi

cd ~/Dropbox/dotfiles/
if [[ $(git status --porcelain) ]]
then
    notify-send -t 0 -u critical "Files in ~/Dropbox/dotfiles/ have been updated. Please push changes to github."
fi
