#!/bin/bash

workspaces=$(i3-msg -t get_workspaces | jq '.[] | {num: .num, focused: .focused}')

for row in $(echo $workspaces | jq -c .); do
    if [ "$(echo $row | jq '.focused')" = true ]; then
        i3-msg -t command [workspace=$(echo $row | jq '.num')] kill
    fi
done
