#!/bin/bash

cd /home/$(whoami) && git clone https://github.com/p-urple/Scripts && echo "isntalled ~/Scripts"

cd /home/$(whoami) && git clone https://github.com/p-urple/st
cd st && make clean install && echo "installed p-urple/st"
cd .. && rm -rf st/ && echo "removed st directory"

cd /home/$(whoami) && git clone https://github.com/powerline/fonts --depth=1
cd fonts && ./install.sh && echo "installed powerline/fonts"
cd .. && rm -rf fonts && echo "removed powerline/fonts directory"

mkdir ~/.config/polybar && mv polybar/config ~/.config/polybar/config && echo "installed polybar/config"
mkdir ~/.config/zathura && mv zathurarc ~/.config/zathura/zathurarc && echo "installed zathura config"
mkdir ~/.config/nvim && mv nvim/init.vim ~/.config/nvim/init.vim && echo "installed nvim/init.vim"
mkdir ~/.config/vifm && mv vifm/vifmrc ~/.config/vifm/vifmrc && echo "installed vifm/vifmrc"
mkdir ~/.config/i3 && mv ie/config ~/.config/i3/config && echo "installed i3/config"
mkdir ~/.config/rofi && mv -R rofi ~/.config/rofi && echo "installed config/rofi"
mv compton.conf ~/.config/compton.conf && echo "installed compton.conf"
mv picom.conf ~/.config/picom.conf && echo "installed picom.conf"
mv .Xresources ~/.Xresources && echo "installed .Xresources"
mv .tmux.conf ~/.tmux.conf && echo "installed .tmux.conf"
mv .bashrc ~/.bashrc && echo "installed .bashrc"
mv .zshrc ~/.zshrc && echo "installed .zshrc"
mv .vimrc ~/.vimrc && echo "installed .vimrc"
