#!/bin/bash

# kill any currently running processes
killall -q ckb-next &
killall -q picom &
killall -q polybar &

# pause to let processes be killed
sleep 0.1

# start apps in background
ckb-next -b &
picom --experimental-backends --config ~/.config/picom.conf -b &
polybar main -r &
polybar secondary -r &

# extra start commands
#compose key
xmodemap -e "kysym Insert = Multi_key"
#start dropbox
dropbox start
